### ISSUE TITLE
Do we need to use connection.close()?

### ISSUE THREAD

**Issue by ffxsam** [ArsenyYankovsky/typeorm-aurora-data-api-driver#45]
First off, thank you for creating this! It's a massive help.

I was wondering if we need to do `await connection.close()` as we normally would with socket connections. Or does it have no effect?

**Comment by ArsenyYankovsky** [comment]
Thank you.
You don't really need to, but you can call `connection.close()` to delete the client object just to free some memory. If you reuse a connection between invocations (assuming you are using lambda) you probably shouldn't do it. 
From a database point of view it doesn't matter if you call `connection.close()` or not since there is no real connection.

**Comment by ffxsam** [comment]
Got it. Thanks!
