### ISSUE TITLE
Any tips on how to get this set up?

### ISSUE THREAD

**Issue by craig006** [ArsenyYankovsky/typeorm-aurora-data-api-driver#7]
Hey, thanks for writing this. I'm sure its going to be a hit with all serverless projects.

I'm trying to get is set up? I assume I need to npm install the typeorm branch with support for this driver as well? How do I do that?

 I tried with 

```
npm install --save typeorm@ArsenyYankovsky/typeorm#feature/aurora-data-api
```

but that fails with:
```
npm ERR! path <OMITTED>/node_modules/typeorm/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod ' <OMITTED>/node_modules/typeorm/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

**Comment by ArsenyYankovsky** [comment]
Hey, 

I tried installing it like you did and got that error. The reason is that I think you can't just pull typeorm from GitHub, you need to build it as well.

As a side note, I think that it's better to push for the PR (https://github.com/typeorm/typeorm/pull/4375) to be merged and wait until then with a setup. 

However, if you absolutely want to start using this project right now it can be done. So what you do is basically pull the project, build it and `npm link` it. That's how I do it in my CI:

1. `git clone --single-branch --branch feature/aurora-data-api https://github.com/ArsenyYankovsky/typeorm.git` - pull the typeorm project
2. `cd typeorm/ && npm i && npm run package && cd build/package && npm link` - build and link the built typeorm project
3. run `npm link typeorm` inside your project folder to point the typeorm dependency to the built project

Let me know if you have any other questions.

**Comment by craig006** [comment]
Thanks for the info, appreciate it. I have replied on that PR as well any ideas what it will take to get it merged? :) 

It will still take a wile for my project to go live. But right now I'm jumping through VPC hoops to get to my RDS instance and its complicating my life. If I understand right data api will allow me to access RDS from outside the VPC? 

Anyways, thought I would start testing the change :)

**Comment by ArsenyYankovsky** [comment]
Hopefully we can get it merged ASAP, the PR as I see it is ready, just need the maintainers to take another look and merge it.
As for VPC the answer is yes you don't need to be on a VPC to use the Data API. So it solves both the connections and VPC-related cold start issues.

**Comment by ArsenyYankovsky** [comment]
Closing as the PR is merged into typeorm and it will be available with the next release.
